name: csr
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - aiohttp=3.6.3
  - async-timeout=3.0.1
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - autopep8=1.5.4
  - blas=1.0
  - boto=2.49.0
  - boto3=1.9.82
  - botocore=1.12.252
  - brotlipy=0.7.0
  - bz2file=0.98
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=3.1.1
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - dbus=1.13.16
  - docutils=0.14
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - gensim=3.8.0
  - glib=2.63.1
  - google-api-core=1.17.0
  - google-cloud-core=1.4.1
  - google-cloud-storage=1.28.1
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.7
  - intel-openmp=2020.2
  - jmespath=0.9.3
  - jpeg=9b
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.6.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.2.5
  - lz4-c=1.9.2
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - more-itertools=4.3.0
  - multidict=4.7.6
  - ncurses=6.2
  - ninja=1.10.1
  - nltk=3.3.0
  - olefile=0.46
  - openssl=1.1.1h
  - pcre=8.44
  - pexpect=4.8.0
  - pillow=5.2.0
  - pip=20.2.2
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.7.3
  - pytorch=1.7.0
  - pytz=2018.5
  - qt=5.9.7
  - readline=7.0
  - s3transfer=0.1.13
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - smart_open=2.1.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - torchaudio=0.7.0
  - tornado=6.0.4
  - typing_extensions=3.7.4.3
  - urllib3=1.25.10
  - wheel=0.35.1
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.9.0
    - alembic==1.4.3
    - antlr4-python3-runtime==4.8
    - astor==0.8.1
    - astunparse==1.6.3
    - biwrap==0.1.6
    - cachetools==4.0.0
    - click==7.1.2
    - cliff==3.4.0
    - cmaes==0.7.0
    - cmd2==1.3.11
    - colorama==0.4.4
    - colorlog==4.5.0
    - coverage==5.0.3
    - dataclasses==0.6
    - entrypoints==0.3
    - filelock==3.0.12
    - flake8==3.7.9
    - fsspec==0.8.4
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.27.2
    - h5py==2.10.0
    - hydra-core==1.0.3
    - importlib-metadata==1.7.0
    - importlib-resources==3.0.0
    - iniconfig==1.0.1
    - joblib==0.14.1
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - mako==1.1.3
    - markdown==3.2.1
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - numpy==1.18.1
    - oauthlib==3.1.0
    - omegaconf==2.0.2
    - opt-einsum==3.2.0
    - optuna==2.3.0
    - packaging==20.4
    - pandas==1.0.1
    - pbr==5.5.1
    - pluggy==0.13.1
    - prettytable==0.7.2
    - protobuf==3.11.3
    - py==1.9.0
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pyperclip==1.8.1
    - pytest==6.0.1
    - pytest-cov==2.8.1
    - python-docx==0.8.10
    - python-editor==1.0.4
    - pytorch-lightning==1.0.4
    - pyyaml==5.3
    - regex==2020.7.14
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sacremoses==0.0.43
    - scikit-learn==0.22.2
    - scipy==1.5.4
    - sentencepiece==0.1.91
    - sqlalchemy==1.3.20
    - stevedore==3.2.2
    - tabulate==0.8.7
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - tensorflow-plot==0.3.2
    - termcolor==1.1.0
    - tokenizers==0.8.1rc2
    - torchvision==0.4.2
    - tqdm==4.43.0
    - transformers==3.1.0
    - wcwidth==0.2.5
    - werkzeug==1.0.0
    - wrapt==1.12.1
    - yapf==0.30.0
    - zipp==3.1.0
